### ISSUE TITLE
UI tweaks for login page (and rest of the app)

### ISSUE THREAD

**Issue by cpg** [amahi/ios#11]
We may need some UI guidelines going forward, but for now, please take note of the following:

 * The logo as it is now is not official. No shadow on the dice, excessive separation with the letters and incorrect font. Please use our [official logo](http://www.amahi.org/press-kit)
 * The background should be either black or very dark for the whole of the app, not just the login page. The Android app did it well and it's comfortable to use in low-light situations, which are common usage.

**Comment by snuff4** [comment]
@cpg Hi, I know we have discussed about the background, but please see this. 

So I made the Launch Screen again with the Official logo this time. Black colour looks amazing with the light colour status bar, so I wanted you to check it out!

I will change the colour of the Setting page accordingly then.😃
 
![simulator screen shot - iphone x - 2018-02-21 at 03 27 06_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/36452722-94cc98cc-16bb-11e8-9c34-4d210eb1aff3.png)

![simulator screen shot - iphone x - 2018-02-21 at 03 27 43_iphonexspacegrey_landscape](https://user-images.githubusercontent.com/30552772/36452726-98259d66-16bb-11e8-8b1c-86ee968b1d7b.png)

Or the dark grey colour like the Android version?
![simulator screen shot - iphone x - 2018-02-21 at 03 51 03_iphonexspacegrey_portrait](https://user-images.githubusercontent.com/30552772/36452808-ecafe8c8-16bb-11e8-9822-8bf91be4a36a.png)

**Comment by cpg** [comment]
even though full black is not often the best good choice, i think it looks good here. good going!

**Comment by cpg** [comment]
This is done. Great going!
