### ISSUE TITLE
offline files issues

### ISSUE THREAD

**Issue by cpg** [amahi/ios#114]
Functionality issues:

- [x] exception in file browser on long press [1]
- [x] once a file is downloaded (I tried with a simple png), it _does_ try to open it, but it's blank. mp4 was able to open, pdf was able to open
- [ ] some file failed to download. there is no indication of the state in the UI. but i know it did not finish downloading (exception). when i try to open it, it does nothing
- [x] exception when trying to share that file (no exception -- debugger just stopped the program)
- [x] exception trying to share a downloaded file [2]

UI:
- [x] the UI is not intuitive (the user has no idea that there are options to long-press and also download. we can work on this later
- [x] progress bar is nice, but it interferes with the slider buttons
- [x] there is no status in the app of what's downloading (after I select a file to download)
- [x] The progress bar appears to stop after a few seconds. If one comes back to the downloads area the progress bar is now updated, though it stops again a few seconds (about 5 or so)
- [x] If one slides to delete a downloaded file but then long-presses and deletes it, the file row vanishes but slider controls stay. attempting to use them causes a crash

1.-
```
2018-06-23 01:13:38.950041-0700 AmahiAnywhere[34084:23761849] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIAlertController (<UIAlertController: 0x1108c9200>) of style UIAlertControllerStyleActionSheet. The modalPresentationStyle of a UIAlertController with this style is UIModalPresentationPopover. You must provide location information for this popover through the alert controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the alert controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
```

2.- 
```
018-06-23 01:45:35.591398-0700 AmahiAnywhere[34124:23768568] *** Terminating app due to uncaught exception 'NSGenericException', reason: 'Your application has presented a UIActivityViewController (<UIActivityViewController: 0x1048d3c00>). In its current trait environment, the modalPresentationStyle of a UIActivityViewController with this style is UIModalPresentationPopover. You must provide location information for this popover through the view controller's popoverPresentationController. You must provide either a sourceView and sourceRect or a barButtonItem.  If this information is not known when you present the view controller, you may provide it in the UIPopoverPresentationControllerDelegate method -prepareForPopoverPresentation.'
```

**Comment by cpg** [comment]
Do we have any indication in case of an error or premature connection issue during the download?

**Comment by cpg** [comment]
Has this been all completed, or can it be deemed as completed?

**Comment by codedentwickler** [comment]
Yes, I think. We can reopen if we find bugs in the current implementation.

**Comment by cpg** [comment]
- [x] When a file from a share is available downloaded already there is an option to "Make unavailable Offline". Aside from the U in unavailable being downcase, this does not appear to work

**Comment by codedentwickler** [comment]
Noted @cpg. I will look into this.

**Comment by codedentwickler** [comment]
@cpg , I think I should remove the "Make unavailable offline" option since we don't want the offline files to have ties to server files.
