### ISSUE TITLE
Improvements on LAN Detection in Auto connection mode

### ISSUE THREAD

**Issue by codedentwickler** [amahi/ios#116]
Currently, the app switches back to REMOTE connection mode inappropriately when LAN is still available. This might be due to the delay before the LAN test completes.

The following updates will make this cleaner and more deterministic
- Whenever the LAN test completes, post a notification with the data(failed/passes)
- All View Controllers observe this notification and update the UI and the current connection state appropriately when it completes.

**Comment by cpg** [comment]
This never happened. We have ended up with a worse system than what we had in the original app. Closing for now as we need to focus on releasing a stable beta.
