### ISSUE TITLE
Music player

### ISSUE THREAD

**Issue by csoni111** [amahi/ios#123]
The app should have a basic audio player to stream and play audio files stored on HDA using the api.

### Features 
- Play/Pause, Forward (15s), Rewind (5s), Next/Previous track controls
- Should display the total track time and elapsed time along with seek bar
- Should be able to extract and display the track metadata (Artist, Album, Track title, Genre, Album Artwork, Track number etc)
- Display of audio controls with artwork on lock screen when playing
- Playlist functionality (play all songs in current directory in loop)
- Music should be played in background thread, so that on minimizing the app it does not stop
- Managing the audio session, so that it handles if some other app plays audio
- Handling audio pause on incoming call/headphone plug out or duck on notifications

**Comment by cpg** [comment]
The current audio player as released in `master` mostly works, however, it has the following issues:

* it takes a long time to load initially (about 15 seconds or so) -- I used a folder with 100 items in it. When using a 10-files folder it takes much less. However, I did verify that the remote was *NOT* being accessed in all 100 (or 10) songs, so it may seem like an entirely app-internal slowdown
* there is no metadata displayed
* when playing a list, there is no way to skip to the next one or previous one
* in the iPad, there are controls on the lock screen to move forward/back, but they appear to do nothing. These controls do not appear in the phone device
* when playing a list there is no way to shuffle the contents. typically people want this often

The player seems very clunky, though reproduction is stable once it starts.

**Comment by ThisIsNSH** [comment]
@cpg @csoni111 I am working on it. 👍

**Comment by ThisIsNSH** [comment]
@csoni111 I am creating new ViewController with suggested features by @cpg for audio instead of AVPlayerViewController. Are we okay with this?

**Comment by csoni111** [comment]
Yes that would be ok!
Instead of writing the whole audio player from scratch, it would be better to leverage some popular library. See if you can find one. @ThisIsNSH

**Comment by iswiftshek** [comment]
Closing this issue as mentioned work is done in #180
Refer to #183 for more on the music player.
