### ISSUE TITLE
beta branch broken after upgrade to swift 4.2

### ISSUE THREAD

**Issue by cpg** [amahi/ios#132]
the beta branch is broken after upgrade to swift 4.2. it does not compile

https://www.dropbox.com/s/sm35y91f4flmnue/Screen%20Shot%202018-10-20%20at%205.13.44%20AM.png?dl=0

**Comment by baquer** [comment]
![screenshot 2018-10-20 at 6 31 01 pm](https://user-images.githubusercontent.com/32494694/47256015-badc9000-d496-11e8-960e-4f6b5bfd15a6.png)
@cpg  replace those lines with the above code , or if you wish i can make a PR for this.

**Comment by cpg** [comment]
thanks @baquer!

let's submit PRs for `beta` only. master is for official public releases.
