### ISSUE TITLE
Thumbnail Previews 

### ISSUE THREAD

**Issue by iswiftshek** [amahi/ios#145]
The app doesn't currently display thumbnails for files. 
Thumbnails depending on the file type should be there, like, for images we can use the image itself. And for files like docs and audio/video, we can use a sample image.

Two tables are to be edited:
- Files Table 
- Offline FIles

**Comment by iswiftshek** [comment]
We can write a few lines of code to do it, but it results in abnormal behavior while scrolling. A fix to that takes the thumbnails a lot of time to show up.

We can instead use libraries like SDWebImage or Kingfisher, which are basically async image downloaders.
I used SDWebImage, and it works like a charm:

![ezgif com-resize (1)](https://user-images.githubusercontent.com/31038198/55041937-6779f980-5055-11e9-9e96-f6fbdec40e64.gif)

I set up sample images for: image, audio, video, and other files types.
How does it look?

**Comment by cpg** [comment]
This is nice. However wouldn't downloading all images (in full) in parallel overwhelm the data line, especially when it's slow?

I.e. we'd have to do something in the server to produce thumbnails and cache them.

Speaking of caching -- will these thumbnails be cached on the app?

**Comment by iswiftshek** [comment]
SDWebImage actually comes with cache support and automatic cache expiration handling.. so, we don't have to worry about a particular url downloading multiple times

**Comment by iswiftshek** [comment]
Yes, thumbnails will be cached on the app.
So the data line should be fine? :)

**Comment by shubhendra-20** [comment]
What if we use multithreading to generate thumbnails so that UI does not get blocked.
It should work in a loop as follows:

`NSOperationQueue *emailsQueue = [[NSOperationQueue alloc] init];

// Add an operation as a block to a queue (second thread)
[emailsQueue addOperationWithBlock: ^ {

    UIImage *thumbnail = [UIImage createThumbnailFromFile:fileName withWidth:310 usingMask:_mask];

    // Get hold of main queue (main thread)
    [[NSOperationQueue mainQueue] addOperationWithBlock: ^ {
        [image setImage:thumbnail];
    }];
    
}];`

**Comment by shubhendra-20** [comment]
What if we use multithreading to generate thumbnails without blocking the UI. It should then not be overwhelming the data line. 
This should work in a loop as follows:

```NSOperationQueue *emailsQueue = [[NSOperationQueue alloc] init];

// Add an operation as a block to a queue (second thread)
[emailsQueue addOperationWithBlock: ^ {

    UIImage *thumbnail = [UIImage createThumbnailFromFile:fileName withWidth:310 usingMask:_mask];

    // Get hold of main queue (main thread)
    [[NSOperationQueue mainQueue] addOperationWithBlock: ^ {
        [image setImage:thumbnail];
    }];
    
}];
```

**Comment by iswiftshek** [comment]
> What if we use multithreading to generate thumbnails without blocking the UI. It should then not be overwhelming the data line.
> This should work in a loop as follows:
> 
> ```
> NSOperationQueue *emailsQueue = [[NSOperationQueue alloc] init];
> 
> // Add an operation as a block to a queue (second thread)
> [emailsQueue addOperationWithBlock: ^ {
> 
>     UIImage *thumbnail = [UIImage createThumbnailFromFile:fileName withWidth:310 usingMask:_mask];
> 
>     // Get hold of main queue (main thread)
>     [[NSOperationQueue mainQueue] addOperationWithBlock: ^ {
>         [image setImage:thumbnail];
>     }];
>     
> }];
> ```

We're already fetching images asynchronously, so the UI won't be blocked.

**Comment by cpg** [comment]
Great job in implementing this in #146 @iswiftshek
