### ISSUE TITLE
Swift whole module optimization

### ISSUE THREAD

**Issue by obitodarky** [amahi/ios#150]
Here is a warning which I have been receiving for some time now. 

![Screenshot 2019-04-01 at 8 27 15 AM](https://user-images.githubusercontent.com/21317964/55301117-8bc04680-5458-11e9-89eb-de38bec4b709.png)

Turns out Whole Module Optimization allows the optimizer to analyze across all the source files in a module to increase compilation times.

More on this [here](https://useyourloaf.com/blog/swift-whole-module-optimization/)

Why aren't we implementing WMO ?

**Comment by cpg** [comment]
How critical or important is WMO?
