### ISSUE TITLE
updating the pods yields various errors

### ISSUE THREAD

**Issue by cpg** [amahi/ios#161]
I am stuck in a pod black hole.

I had to update my working environment to be able to compile the app. xcode was complaining that the pods were out of sync and needed to be installed. I had trouble with the pod command. Then I decided to reinstall cocopods because the pod command was clearly busted. The next error I was getting was:

```
$ gem install cocoapods
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.33 given
```
and I could not find a way to fix this at all. Even reinstalling ruby (2.4.1) or installing a new ruby (2.6.0).

Eventually I was able to use bundler with a tiny `Gemfile` and use bundler to install `cocoapods` through the gemfile. However, I then got a complaint that

`[!] CocoaPods could not find compatible versions for pod "Alamofire":`

I tried to update just that pod, but then I got `no such module` errors with `SDWebimage` (which appears to have had a major update from v4 to v5) and  `Lightbox` even after cleaning the build folder in xcode. 

Next I updated the whole lot of pods. It appears only `Alamofire` needs update?

Anyway, I am still getting these errors.

... so I got trapped into this pod black hole and I am stuck now.

I committed what I was able to do in the `pod-update` branch.

**Comment by codedentwickler** [comment]
@cpg Looking into this issue.

**Comment by csoni111** [comment]
**To reinstall cocoapods:** https://stackoverflow.com/a/48335801

**For `CocoaPods could not find compatible versions for pod "xxx"`:** Run `pod repo update` -> `pod install`

**For `no such module 'xxx' errors`:** https://github.com/amahi/ios/issues/163

**For `SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'xxx')`:** https://stackoverflow.com/a/55585598

**Comment by cpg** [comment]
It was because I [opened the wrong file](https://stackoverflow.com/questions/30809206/cocoapods-pod-install-modules-cannot-be-imported) when opening Xcode. I should have opened it by clicking `AmahiAnywhere.xcworkspace`
