### ISSUE TITLE
URLs with + in the original file seem to fail to open

### ISSUE THREAD

**Issue by cpg** [amahi/ios#167]
I think long URLs are not working.

Once a folder, file and various parameters like session are added, I found that URLs can be fairly long. I came across one that by the time the `GET /XYZ` gets to the server, the `/XYZ` is 245 chars long.

I do know that the file is a playable `mp4`, however, when trying to open the file in the app, it tries to open it and it abruptly stops.

I don't have a way to get the debug log at the moment. It may be easily reproducible by making a folder of long name.

**Comment by cpg** [comment]
never mind, it looks like it's a [server isue](https://github.com/amahi/amahi-anywhere-fs/issues/21)

**Comment by cpg** [comment]
Looks like [it may be client related](https://github.com/amahi/amahi-anywhere-fs/issues/21#issuecomment-485517449), not related to lenght but proper escaping of URLs.

**Comment by codedentwickler** [comment]
Okay, I'll look into this.
