### ISSUE TITLE
App is not building due to missing ApiConfig.swift file (new contributors please READ)

### ISSUE THREAD

**Issue by imjog** [amahi/ios#18]
ApiConfig class is using in many places like ApiEndPoints, AuthService etc. Xcode is showing that this file is missing. Why is this file deleted? If there is a reason then what is the replacement?
![screen shot 2018-02-22 at 20 51 08](https://user-images.githubusercontent.com/20956124/36546751-39fffe2c-1812-11e8-9a99-ddc2d94e307b.png)

**Comment by snuff4** [comment]
Yes, because of some security issue. @codedentwickler can help you out.

**Comment by cpg** [comment]
Email support at amahi dot org a copy of this file. This file has sensitive credentials.

**Comment by imjog** [comment]
@cpg can we mention this (refer this issue) on Readme.md?

**Comment by devjdg** [comment]
Would it be helpful if a sample ApiConfig.swift file was included in the repository (eg. formatted as a markdown file). This is just to have a uniform setup. Just a suggestion.

**Comment by cpg** [comment]
We looked at a couple of options with gitignore and other, and I just tried again, with fatalError().

I have no idea how having markdown would work at all.

Sadly, any new changes are NOT .gitignored and surely someone, sometime, will commit this file with dev credentials.

**Comment by devjdg** [comment]
As per suggestion, using a markdown as an example file only just to show the ApiConfig template. Another workaround possibly is through the implementation of .gitattributes and custom filters.
