### ISSUE TITLE
Odd behavior in Downloads 

### ISSUE THREAD

**Issue by iswiftshek** [amahi/ios#181]
![GIF-2019-06-09-16-30-57](https://user-images.githubusercontent.com/31038198/59163586-82bab800-8b20-11e9-878d-d24af05e4d99.gif)

To reproduce this behavior, delete a file in downloads while another file is being downloaded. The thumbnail of the deleted file will try to become the thumbnail of the ongoing download as shown above until downloading is complete.

**Comment by cpg** [comment]
I believe I have seen this one before. Good catch.

**Comment by cpg** [comment]
Actually, this happens without deleting any file in downloads.

One way to reproduce this flickering is to 1) have some file(s) in downloads already, 2) start downloading a (non-trivial) file (so it takes time and you can experience this) and 3) go to the downloads area. The file is downloading ok, but

 * the icon seems to be from one of the existing downloads (not necessarily the latest downloaded one, at least in my case) and 
 * the icon flickers incessantly

**Comment by iswiftshek** [comment]
Right. And it seems to be flickering randomly, like, it could take any one icon from the list or it could take 2, 3.. at random
