### ISSUE TITLE
Improvements in the Music Player

### ISSUE THREAD

**Issue by iswiftshek** [amahi/ios#183]
The music player has all the basic features (#180) like repeat, shuffle, next, prev, playback from control screen and lock screen, but there is a lot of scope for improvements for better user experience.

**Improvements to be done**

- [ ] Cache the Artwork 
- [x] Fix the jumpy time slider
- [ ] The slider on the lock screen/control screen changes the position of the file playing, but the changes in position from the music player won't reflect on the former
- [ ] The initial time to load and start the music player should be reduced 
- [x] Manage audio session if the user plays audio on some other app 
- [x] Handle the audio session with Bluetooth devices
- [x] Improve the transition between the audio files (all info on the screen should be in better sync, like the way music player acts when playing downloaded audio files)

**Could be done**
- [x] ~Close button be added in place of "Done"~
- [ ] Show the current volume on the screen
- [ ] More metadata (Album name, Genre, etc.)

**Comment by anubhavsingh16** [comment]
What about this issue? 

Is it still open?
