### ISSUE TITLE
Show available space for downloads

### ISSUE THREAD

**Issue by cpg** [amahi/ios#191]
We should find a way to show the available space for downloads.

One simple place to show it would be in the line underneath the "Clear Temporary Downloads" which at the moment just says `Current size: XYZ KB` and could also feature (separated by a middot with spaces or similar) `Available size: ABC KB`

**Comment by Marton-Zeisler** [comment]
and what is the available space for? How much space is left on the HDA server?

**Comment by cpg** [comment]
No on the phone, so one can tell how many files/space one can take on the go
