### ISSUE TITLE
Issues updating SDWebImage to 5.x

### ISSUE THREAD

**Issue by cpg** [amahi/ios#194]
The `SDWebImage` pod needs to be updated (currently from 4.4.6 -> 5.0.6) and the change causes some build-time errors:

![Screen Shot 2019-07-03 at 10 15 24 AM](https://user-images.githubusercontent.com/9907/60575342-a79af780-9d7b-11e9-82a9-dea4a2d2498a.png)

```
.../AmahiAnywhere/AmahiAnywhere/Utils/ThumbnailGenerator.swift:22:47: Cannot call value of non-function type 'SDWebImageManager'
```

**Comment by Marton-Zeisler** [comment]
This has been fixed, so this issue can be closed :)
