### ISSUE TITLE
Add "Forgot password?" link

### ISSUE THREAD

**Issue by snuff4** [amahi/ios#20]
A small button in the login view which comes after the login fails once, which leads to this [link](https://www.amahi.org/forgot).

**Comment by cpg** [comment]
Has to be either a small link or a small button that is out o the way (e.g. bottom of the screen).

**Comment by snuff4** [comment]
Something like this, from the Android app.

![whatsapp image 2018-02-24 at 06 30 02](https://user-images.githubusercontent.com/30552772/36623617-3cba2f0a-192c-11e8-967f-fc320dbb1166.jpeg)

**Comment by cpg** [comment]
looks good!

**Comment by snuff4** [comment]
![screen shot 2018-02-25 at 5 44 13 am](https://user-images.githubusercontent.com/30552772/36636556-17f050fa-19ef-11e8-9b08-bc29c097e071.png)

**Comment by snuff4** [comment]
![screen shot 2018-02-25 at 5 46 09 am](https://user-images.githubusercontent.com/30552772/36636563-3b8fd2f6-19ef-11e8-8d06-ea9fd1452ae0.png)

**Comment by cpg** [comment]
Closed by #24, thanks!
