### ISSUE TITLE
App crashes when playing multimedia in iOS 13

### ISSUE THREAD

**Issue by iswiftshek** [amahi/ios#228]
Looks like in iOS 13 Apple has done a few changes that causes the app to crash when we play a music/video file. 
![Image 10-08-19 at 11 24 am](https://user-images.githubusercontent.com/31038198/62820086-fad34780-bb7c-11e9-8311-09a57ac486d9.JPG)

It comes from the MPRemoteCommand(s) in `AudioPlayerViewController.swift` & `VideoPlayerViewController.swift`

**Comment by cpg** [comment]
Just to be clear. The fix has to work on prior versions of iOS, ideally without the app having to check the OS version.

**Comment by anubhavsingh16** [comment]
@iswiftshek  I can't find any problem when I play videos in iOS13

**Comment by anubhavsingh16** [comment]
@cpg @iswiftshek I'm working on this issue.
