### ISSUE TITLE
Adding Network Singleton class for all the API calling

### ISSUE THREAD

**Issue by imjog** [amahi/ios#23]
Since we are using alamofire for API calling and other network stuff, I created a Network.swift file where I implemented all the methods like `post`, `get`, `postWithFormData`, `put`, `patch`, `delete`, `uploadFiles`, `downloadImage` etc with alamofire. All the methods have completion handlers that return parsed JSON, status code, error etc. I created a singleton of this class. We just have to call `Network.shared.post(..)` (whatever we require). Everything else is handled by Network class.
Benefits:

- Well written methods for all HTTP requests.
- Easy response code and error handling.
- Do not need to import Alamofire in ViewControllers and other places. We just have to call singleton method.
Should I add network file to project? We can discuss and give try to this!

**Comment by codedentwickler** [comment]
Looks like a good idea @imjog. I don't think we need it for all the methods like patch or delete, I doubt we will use them but it will be good to see this when you PR so we can all review

**Comment by codedentwickler** [comment]
Ooh, Great then.

**Comment by imjog** [comment]
Thank you @codedentwickler @cpg :)
After making some changes I will make a PR. Also, I am adding a new pod called `AlamofireImage` (AlamofireImage is an image component library for Alamofire) which I used for writing methods for `uploadFile` and `downloadImage` and some other methods.
Link to AlamofireImage pod: https://github.com/Alamofire/AlamofireImage

**Comment by imjog** [comment]
I created a PR #25 for this issue. Please review it :)
Also, I did not add `AlamofireImage` pod because there was only one method name `downloadImage` using this pod so I removed the method. I will add this method again when we require.

**Comment by cpg** [comment]
Closing for now. I think AlamoFire may do for now, we can reopen this and revise the use of something like #25 when needed.
