### ISSUE TITLE
close button should be on the left

### ISSUE THREAD

**Issue by cpg** [amahi/ios#246]
Based on an informal check, the close button (or Done in some apps), is on the left side of the screen on most apps, including non-multimedia apps. This appears to be the standard.

We should swap our top two buttons (close button and menu).

**Comment by pushpinderpalsingh** [comment]
Here, which buttons are we talking about?

**Comment by anubhavsingh16** [comment]
@cpg if you are taking about Done button in VideoPlayer then it is already on the left side.

**Comment by vaibhavbisht06** [comment]
@cpg There is no such Close button, yeah there is done button which is already in fixed.

**Comment by anubhavsingh16** [comment]
Ok
