### ISSUE TITLE
When an alarm goes off, the player appears to lose audio and wobble play

### ISSUE THREAD

**Issue by cpg** [amahi/ios#247]
The player is playing a movie. If an alarm comes in during that time, the player appears to lose audio and wobble play.

We thought we had this behavior fixed in the past, but it's not working well.

To reproduce, set a 30 second alarm and play a movie.

**Comment by anubhavsingh16** [comment]
@cpg I'm working on this issue.

**Comment by anubhavpulkit** [comment]
@cpg It is already solved.
