### ISSUE TITLE
pod install error

### ISSUE THREAD

**Issue by anubhavsingh16** [amahi/ios#249]
Analyzing dependencies
Cloning spec repo `cocoapods` from `https://github.com/CocoaPods/Specs.git`

stuck on cloning spec repo.

@aljachimiak @cpg @megabitdragon @sukhbir-singh

**Comment by codedentwickler** [comment]
Hi, @anubhavsingh16 hope you have fixed this issue now.

**Comment by anubhavsingh16** [comment]
> Hi, @anubhavsingh16 hope you have fixed this issue now.

@codedentwickler actually no I can't fixed 
Showing Recent Issues
/Users/anubhavsingh/ios/AmahiAnywhere/Pods/Target Support Files/Pods-AmahiAnywhere/Pods-AmahiAnywhere.debug.xcconfig: unable to open file (in target "AmahiAnywhere" in project "AmahiAnywhere")

**Comment by codedentwickler** [comment]
Do a clean.
Close Xcode.
Navigate to project directory where the Podfile exist.
Do pod update/pod install
Open `AmahiAnywhere.xcworkspace`

**Comment by MANI14011998** [comment]
@anubhavsingh16  hey Buddy 
I am too facing the same problem so i Just update the CocoaPod Version or pod version plus 
and it works.

**Comment by anubhavsingh16** [comment]
> Do a clean.
> Close Xcode.
> Navigate to project directory where the Podfile exist.
> Do pod update/pod install
> Open `AmahiAnywhere.xcworkspace`

ok I'm going to try again

**Comment by anubhavsingh16** [comment]
> @anubhavsingh16 hey Buddy
> I am too facing the same problem so i Just update the CocoaPod Version or pod version plus
> and it works.
okk i will try

**Comment by anubhavsingh16** [comment]
@codedentwickler @MANI14011998 thanks finally build successfully😍

**Comment by aviralx10** [comment]
hey @anubhavsingh16 facing the same issue.. always get stuck on cloning spec repo...
can you please tell how to cope with this issue?

**Comment by anubhavsingh16** [comment]
@aviralx10 I explain this in my PR #251

**Comment by aviralx10** [comment]
@anubhavsingh16 thnx ..figured it out
