### ISSUE TITLE
Fix Swift Compiler Error

### ISSUE THREAD

**Issue by harshitjindal** [amahi/ios#255]
Initial build fails with error "Call can throw, but it is not marked with 'try' and the error is not handled" in AmahiAnywhere/Managers/ConnectionModeManager.swift > `Reachability()`.

Using Xcode 11.3, here's a screenshot.
<img width="1440" alt="Screenshot 2020-01-11 at 9 05 47 PM" src="https://user-images.githubusercontent.com/11704992/72206619-379dc480-34b6-11ea-9060-d5584b508e84.png">

**Comment by pushpinderpalsingh** [comment]
already fixed by @anubhav16 in pr #250
