### ISSUE TITLE
Reusable components, style guideline and suggestions

### ISSUE THREAD

**Issue by imjog** [amahi/ios#26]
Development of this project is started just few days ago so I want to create some Reusable components that can be applied to iOS applications developed throughout the organization. Also, I want to propose swift style guide and best ios development practices.

**Reusable Components**
Rather than calling functions and methods again and again, we can create reusable components. This will help us writing clean code and save our time.
- Extension file - add a new file name Extension which will contain Extension of some useful `UIKit` and some other classes. I added to Dictionary extension `unionInPlace` in `Network.swift` file, this should be in Extension file. As the development get process, we will need a lot of Extensions.
- Views file - here we will create views that we will need at many places in the app. Like alertView, noInternetConnectionView, common error view, networkActivityIndicatorView etc according to our requirements.
- AppConstants - we can define all the constants like asset images names, userDefaultsKey etc type of constants which is common for the application.
- How about define Endpoints and Network call all in the same file. Currently, Endpoints are not defined in a good way. can I make a PR Regarding this?

Some other thing I will add in the list.

**Style Guidelines**
To make the code more cleaner and understandable we should follow Swift Style Guide and some best practices for iOS Development. This will help new contributors a lot. I always try to follow [this Swift Style Guide](https://github.com/imjog/swift-style-guide). For best iOS practices I want to suggest [this good practices](https://github.com/futurice/ios-good-practices).
 
**Suggestion**
I learn some good things about ios development during last internship and Swift meetups. Some of them I share above and some I want to add here -
 - for small purpose rather than adding pods to our project, we can directly drag the file to our project so that we can modify according to our need. Also, many pods contain functionality that is all not useful for us. Please be clear that I am talking just about small pods that can be draggable. Like for parsing JSON I added a SwiftyJSON file to project rather than adding a pod. Rather than using `SkyFloatingLabelTextField` as a pod, we can drag this file to our project. 
- rather than using string, int or other file constants directly we can create a private struct on the top of the ViewController file. This will make `ViewController` code a lot cleaner and easy to change the value of constants.
Ex.
```
fileprivate struct DefaultConstants {
         static let buttonCornerRadius: CGFloat = 8.0
         static let buttonTitleText: String = "Button"
         static let imageURLString: String = "https//.."
}
```
- Put all view controllers in one group, all views in same group etc. 
- Use PDF file at the place of PNG files. PDFs are vectors so we only need to add 1x file and it will look good for all the resolutions. This is recommended by Apple. Also, we do not require 1x, 2x and 3x file for all icons and images.
- We can use some marketplace tools like Travis CI etc that will make sure everything in PR is perfect before merging it.
I will add some more points to the list. Everyone suggestions are welcomed so that we can build a great app. @codedentwickler @cpg

**Comment by imjog** [comment]
@cpg We can implement the things you agreed.
- We can mention about Style Guide and good practices on our readme.md file or a new file for contribution guideline.
- About PDF files - I didn't read on the internet but I learn this thing in meetup I attend in Bangalore, India. Also, last intern place suggested me this that why I suggested here.
- Extension files - I am suggesting about the extension of `UIKit` and `Foundation` classes. Please be clear that Extension of our `ViewController` and other custom classes should be in the same file. You can read about swift extensions [here](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Extensions.html). Also, you can have a look at [SwifterSwift](https://github.com/SwifterSwift/SwifterSwift) repo for reference.
- By perfection, I meant that If builds are passing or not like thing :D

**Comment by cpg** [comment]
I would suggest you add a link to the coding style guide to the README through a PR.
