### ISSUE TITLE
App Crashes When I try to login

### ISSUE THREAD

**Issue by aviralx10** [amahi/ios#266]
The App crashes immediately when I try to login on the simulator .. even though I m able to login on my phone...This error keeps on coming.. pls help..
Fatal error: You may need to get dev credentials to be able to properly login into amahi.org

**Comment by vaibhavbisht06** [comment]
**@aviralx10**  The app crashes immediately when you try to log in on simulator. and give you an error:  You may need to get dev credentials to be able to properly login into  **amahi.org**
You need to mail to amahi.org asking them for Developer credentials and paste them over **ApiConfig** file. 
**Remove your credentials before committing the code.**

**Comment by aviralx10** [comment]
thank you :)
