### ISSUE TITLE
Sign In Error on Login Page

### ISSUE THREAD

**Issue by yugantarjain** [amahi/ios#281]
I'm unable to sign-in on the Amahi iOS app master branch, any help would be appreciated.
Simulator Used: iPhone 11 Pro Max - 13.3

My login credentials are working perfectly on the Amahi app on the App Store.
However, when I build the project locally on my device a network error occurs while signing in.

Based on the error message I've realised it is a GENERIC_NETWORK_ERROR as used in the LoginPresenter.swift file.

Also, I've commented the fatal error command in ApiConfig.swift file

**Comment by anubhavsingh16** [comment]
Hi @yugantarjain This is not an issue you need correct credentials for login.
