### ISSUE TITLE
Settings Screen transition animation inconsistent with the hamburger button

### ISSUE THREAD

**Issue by ShresthPratapSingh** [amahi/ios#282]
The hamburger button is present on left while the settings screen transitions from the right side This is bad UX and feels odd.(refer Gif)
![issue gif](https://user-images.githubusercontent.com/32341862/76253539-de150480-6270-11ea-827b-7a6353562466.gif)

**Comment by ShresthPratapSingh** [comment]
I'm working on this issue

**Comment by cpg** [comment]
Not an issue in `beta`
