### ISSUE TITLE
App crashes during launch on iOS 13.3.1 devices

### ISSUE THREAD

**Issue by ShresthPratapSingh** [amahi/ios#283]
On building the app on iOS 13.3.1(iPhone 8 plus) device app crashes during launch with the debug description as shown below. I tried building the app on iOS 12.4.1(iPhone 7) it works fine.

**Debug Description :** 
**dyld: Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/AmahiAnywhere
  Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire'
	/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire'
	/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1
	/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire: code signature invalid for '/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire'
	/private/var/containers/Bundle/Application/96785ED0-198D-4E8B-95A5-EA22305F205E/AmahiAnywhere.app/Frameworks/Alamofire.framework/Alamofire: stat() failed with errno=1**

**Comment by anubhavsingh16** [comment]
@ShresthPratapSingh Because of your Podfile is of the master branch this issue arrives. To solve this issue you have to copy the Podfile of beta branch.
