### ISSUE TITLE
No Activation Email

### ISSUE THREAD

**Issue by FelSlade** [amahi/ios#309]
Hiya Amahi Team

Am to get Amahi from the Website, I register <MyUserName>.yourhda.com and set a Password. I hit the Start Now Button..... Nothing, No Email in Main or Junk Mail. 

Is there a way to help me with this please.

Kind Regards
FelSlade

**Comment by cpg** [comment]
Well, the main site is www.amahi.org and email has been working without any outages for a long long time. We keep an eye on the email system all the time. Email support if you still have any issues. Thanks and apologies for the belated response.
