### ISSUE TITLE
App core design, look and feel

### ISSUE THREAD

**Issue by cpg** [amahi/ios#31]
We have a great login screen and flow. This issue is for coming up for a design (or at least several sketches) of what the app should look once the user is logged in, the **core** design.

We need to work on the way the core of the app needs to look and behave. We may need to survey popular apps that do similar things as to what we need (hierarchical navigation, within a main top level) and get some inspiration from them..

We may have to mock up a few designs to get us going an choose something that we feel works well.

At the top level we need:

1) Relatively easy access to the settings area. This may not be needed in all views, maybe perhaps only at the top level. One possibility is a hamburger menu, or a gear icon.

2) For servers, we only need something simple, though long-term we may want to have many servers (once we get server-sharing working)

3) For shares, we need a top level list and recursive navigation capabilities, with opening/handling of many types of files, thumbnail and metadata display. Our Android app does this nicely, so it may be a  good reference (_not_ for being copied at the pixel level, but the navigation and look/feel of it).

4) It's crucial that the app handles many file types well. Specifically audio play, video play, PDFs, other docs, etc., possibly launching existing apps (e.g. a `.mobi` file should be opened with an ebook reader an let the user choose, maybe). Android does this at the OS level (i think) where the user chooses the app to handle an whether it should be done "always" or "just once". I don't think iOS does this. One example of a top-tier app that does a lot of this is Dropbox.

5) For apps, we need a list (typically a handful of apps, perhaps a dozen) and the ability to launch an embedded browser into each app, where each browser has to be easy to exit, however, cookies and perhaps even context (what url it was) may need to be remembered.

6) The app should work well in tablets as well as phones, in both landscape and portrait orientations. It's hard to make it all work in every single case, but we should be at least be making things relatively easy in the small form factor as well as portrait mode.

**Comment by baquer** [comment]
@cpg i made the UI of Setting Area , check it .
![screen shot 2018-03-12 at 1 42 53 am](https://user-images.githubusercontent.com/32494694/37258003-168e8de0-2597-11e8-883c-f72df2d9f642.png)
![screen shot 2018-03-12 at 1 42 58 am](https://user-images.githubusercontent.com/32494694/37258007-1e463312-2597-11e8-9e5e-06b87390c879.png)

**Comment by iswiftshek** [comment]
Can I work on Issue 6 (making the app work well in both landscape and portrait orientations), if anyone's not working on it currently?

**Comment by shubhendra-20** [comment]
@cpg I am looking forward to the design. Can you suggest some other popular apps which function the same way?

**Comment by cpg** [comment]
We have worked on this on `beta` and it's mostly ready to release to our user base.
