### ISSUE TITLE
App Crash when trying to reload shares

### ISSUE THREAD

**Issue by ShresthPratapSingh** [amahi/ios#315]
No shares are loaded in Welcome to Amahi server and app crashes when trying to refresh and load shares

![Screen Recording](https://user-images.githubusercontent.com/32341862/87534620-e6180180-c6b3-11ea-9cdf-7a3c288f5308.gif)

error message:

`[Error Domain=com.alamofirejsontoobjects.error Code=1 "Data could not be serialized. Input data was not json." UserInfo={NSLocalizedFailureReason=Data could not be serialized. Input data was not json.}]
Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/shresth/Desktop/ios/AmahiAnywhere/AmahiAnywhere/Data/Remote/ApiCalls/ServerApi.swift, line 110
2020-07-15 15:57:55.653991+0530 AmahiAnywhere[17943:632607] Fatal error: Unexpectedly found nil while unwrapping an Optional value: file /Users/shresth/Desktop/ios/AmahiAnywhere/AmahiAnywhere/Data/Remote/ApiCalls/ServerApi.swift, line 110`

There's a forced unwrap on serverRoute variable on line 110 which is why the app crashes when it's found nil i.e, some unhandled error.

**Comment by ShresthPratapSingh** [comment]
I've tried debugging the issue , here's what I've found :

The network call to get shares return a response code - 408 : (request timed out)

The call stack for the api request and endpoints are shown below:

![Network request Call Stack](https://user-images.githubusercontent.com/32341862/87543899-2af76480-c6c3-11ea-9242-f63e5d1e3fd5.png)

![Api request Params](https://user-images.githubusercontent.com/32341862/87544019-5f6b2080-c6c3-11ea-90c9-d496923a05a6.png)

_<proxy url> refers to the url provided in APIConfig.swift file_

**Comment by cpg** [comment]
If your HDA is not connected and you are accessing it through the Amahi VPN proxy, a `408` is appropriate, hence the app should not crash.

We do not recall having experienced this in the past, however, it sounds like a bug and a message should be displayed to the effect that the HDA could not be reached.

**Comment by cpg** [comment]
This is the [spec for the 408](https://github.com/amahi/amahi-anywhere-specs#error-handling).

**Comment by anubhavsingh16** [comment]
I'm facing the same issue after remote update.

**Comment by ShresthPratapSingh** [comment]
@cpg I can access the shares on my own hda server which is running from a VM but I can't access the default amahi demo server due to 408 now which I was able to access earlier(same issue is with @anubhavsingh16 i think). Any suggestions for how can we get the demo server working again?

**Comment by cpg** [comment]
Let me be clear:

1. the app should not crash when a `408` return is appropriate, hence the app _should not crash_.
1. When one has a local HDA, it should access it directly, not through the VPN, but it any case, it _should not crash_.
1. We will be getting the VPN proxy up and running as soon as we can
1. the app _should not crash_

**Comment by anubhavsingh16** [comment]
Yeah, I understand this is not an app crash.
