### ISSUE TITLE
recent files need to be able to be cleared

### ISSUE THREAD

**Issue by cpg** [amahi/ios#324]
The user should be allow to delete them from the list, for privacy as well as practical reasons (e.g. many files may no longer exist, there are too many recent files, etc.).

**Comment by anubhavpulkit** [comment]
Can we Add swipe to delete method? like this
![issue](https://user-images.githubusercontent.com/47811606/88658515-31d59c80-d0f1-11ea-9dd4-9a30e35727b2.png)

**Comment by cpg** [comment]
That is what I meant.

- I do not like the word `Delete` however. I think maybe `Clear` may be better (or `Remove`, but I am not sure; it also gives the impression of deleting/removing the file from the server)
- there is a download action, both there and in the pop-up menu. Why is it not there in your screenshot? Are you proposing deleting it? (bad idea)
- The `Clear` action also should be in the pop-up menu

**Comment by anubhavpulkit** [comment]
Can we add a single button to clear all recent files? I think using a single button to clear all the files from the recent section is a good idea.

**Comment by cpg** [comment]
It's not a bad idea and it's not incompatible. Individual files need to be cleared too.

**Comment by anubhavpulkit** [comment]
Recent File clear methods:
- Individual files cleared option (by a swipe to clear)
- All files cleared by clicking a single button

**Comment by anubhavpulkit** [comment]
![clear](https://user-images.githubusercontent.com/47811606/88842833-c1687180-d1fd-11ea-9f08-7f1c7dcb0314.png)  ![clear 2](https://user-images.githubusercontent.com/47811606/88842857-cb8a7000-d1fd-11ea-8063-097b9122e9da.png)

@cpg Which one is better swipe 1. `right to left` or 2. `left to right` 
In my personal opinion 2. `swipe left to right` is better one.
