### ISSUE TITLE
When playing music from the recent files, the up-next area appears to be in a high-cpu infinite loop

### ISSUE THREAD

**Issue by cpg** [amahi/ios#331]
**Describe the bug**
When going to the recent files, the user can play music from a recent file. The player comes up and the up-next area appears to be in a high-cpu infinite loop, probably because the what's next data structures are empty?

**To Reproduce**
1. Go to recent files (go to some music first and play it to insert it in recent)
2. Tap on a music file
3. See the "Up Next" area flashing repeatedly

**Expected behavior**
I am not sure -- UX wise, what should be done? Maybe not show any "up next" panel?
Or ..?

**Comment by ShresthPratapSingh** [comment]
Yes, I think it would be better UX wise to not show “up next” queuing  for files in recents tab.

Reason behind this:
In the current implementation when a user taps on a file in recents tabs all the files are scanned in a loop  in which `mimeType == "audio"` and then queued in the DS for audio player to play.

If we really want to show up next then we should have a hybrid player that supports image/ video/ audio. That way we could be showing the files that are actually present  next in the recents tab and not just skip to files of a single type.
