### ISSUE TITLE
Show size and percentage downloaded when downloading a file

### ISSUE THREAD

**Issue by tusharjindal353** [amahi/ios#347]
### Description: ###
The Download will be more better and informative if we can add size and percentage downloaded of a file in downloads screen.
In Current version It is only showing a progress bar.

![Simulator Screen Shot - iPhone SE (2nd generation) - 2020-08-11 at 14 40 38](https://user-images.githubusercontent.com/24813267/89882014-da9cf500-dbe3-11ea-84eb-5acb0820ae82.png)

**Comment by tusharjindal353** [comment]
@cpg Can you have a look at this?

**Comment by cpg** [comment]
I had a look. You are not wrong.

**Comment by tusharjindal353** [comment]
@cpg I would love to work on this improvement.

**Comment by tusharjindal353** [comment]
@cpg Can you assign this improvement to me?
