### ISSUE TITLE
Descriptions in the walkthrough UI overlap in landscape orientation

### ISSUE THREAD

**Issue by anubhavpulkit** [amahi/ios#353]
- The description text in landscape orientation has overlapped the baseline.
- The page controller action is not working. The Ui is not changing with the page controller.
- Color of next button is black which look quite unordered.(*change to white or make skip and next button blue color)

### Screenshots/ gif

- Color of next button
![walkthrough1](https://user-images.githubusercontent.com/47811606/90319705-1d4e2c80-df58-11ea-9980-a472c4b611e4.png)

- Description text issue
 ![walkthrough](https://user-images.githubusercontent.com/47811606/90319707-20e1b380-df58-11ea-8c8c-c6d864244a01.png) 

- Page controller action
![walkthrough 2](https://user-images.githubusercontent.com/47811606/90319777-da408900-df58-11ea-8b93-089e78286f42.gif)

**Comment by ShresthPratapSingh** [comment]
To easily test Walkthrough Screen UI:

- Go to `SettingsViewController.Swift` > `internal func signOut()`
- In `signOut()` **Comment out the following line of code** 
   `let loginVc = self.viewController(viewControllerClass: LoginViewController.self, from: StoryBoardIdentifiers.main)`
- In place of the code we just commented **add the following code**:
  `let loginVc = UIStoryboard(name: "Main", bundle: nil).instantiateViewController(withIdentifier: StoryBoardIdentifiers.walktrhoughViewController)`
- Build and run. When you sign-out from Settings tab, Walkthrough screen is presented hence no need to uninstall and reinstall the app everytime.

### This code is purely meant to make testing easy and should NOT be commited.
