### ISSUE TITLE
login requirements

### ISSUE THREAD

**Issue by cpg** [amahi/ios#4]
the login requirements are as follows:

UI:
 * logo, up top, typically
 * "Username or email" field, should show an email keyboard
 * "Password" field, regular keyboard, secure
 * those two fields must not be occluded by the keyboard pulling up
 * "Login" button

Once these fields collected, the app has to use Oauth 2.0 to login.

The details of the url to use have to be loaded from a file in the code e.g. a definition file or something, however, the real credentials *must not be committed in the git repo*, as they are not public information:

 * amahi login url
 * amahi proxy url
 * client id
 * client secret

once logged in, the user must remain logged in until the user taps on some logout button/link (typically under some settings page that will include among other things this logout).

until it has such a functionality, the logout button/link can be anywhere, e.g. the header.

**Comment by codedentwickler** [comment]
I will work on this.

**Comment by codedentwickler** [comment]
**Summary:**
Implement OAuth 2 for login

**Expected Behaviour:**
User must be able to Login to the App and stay logged in until the user taps logout button.

**Steps:**
1. Add Necessary dependencies for Networking. I'm considering using [Alamofire](https://github.com/Alamofire/Alamofire) for Networking and [EVReflection](https://github.com/evermeer/EVReflection) for Parsing the JSON responses into Response Objects.

2. Add a loading indicator during Http requests. I'm considering using [MBProgressHUD](https://github.com/jdg/MBProgressHUD) to achieve this easily.

3. Prevent issues of keyboard sliding up and cover the input fields. [IQKeyboardManager](https://github.com/hackiftekhar/IQKeyboardManager) handles this easily with fewer lines of code for the whole app.

4. Setup a Base ViewController to implement all the common feature of all View Controllers, like showing errors, showing and dismissing loading and more

5. Add a configuration file that will contain the actual credentials as stated above.

6. Implement OAuth 2 and use user details to log into the app.

7. Store access token and User data on App using UserDefault when the User Logs to know current logged in user information

8. Clear Stored information when the user is logged in.

9. Get Access token when the token expires or use refresh token if applicable.

**Comment by cpg** [comment]
Plan looks good. I would base your work on #2 while that is being finished.

**Comment by codedentwickler** [comment]
Okay thanks. I will leave @csoni111 to complete what he is working on. I will go on with the setup for now and connect storyboard when his PR is merged

**Comment by csoni111** [comment]
@codedentwickler I am not working on anything!

**Comment by codedentwickler** [comment]
Oops sorry about that, I meant @baquer work on updates to his PR on the Login page.

**Comment by baquer** [comment]
**summary**
implementing OAuth 2 for login
**Expected Behaviour**
user login 
**Summary**
we can implement OAuth 2 by using Cocoapods 'AlamofireOauth2'
and sliding of keyboard by 'IQKeyboardManager'

**Comment by codedentwickler** [comment]
@cpg I am assuming the ios OAuth flow is like the one implemented on the Android. I will explain what I understand at the moment. Correct me if I'm wrong.

Steps:

- User opens app. If it is the first launch or access token has expired, **GET ACCESS TOKEN**
- Store the access token and expiry time locally.
- The user provides username/email and password.  Use access token to make a request for LOGIN 

I am currently assuming this is the OAuth response
`{
  "access_token": "AYjcyMzY3ZDhiNmJkNTY",
  "token_type": "bearer",
  "expires": 3600
}`

Is this correct? 

It will be easier if you can create a temporary Client id and Secret for me to test what I am working on. Also the API documentation or simply the URLs for OAuth and Login

**Comment by cpg** [comment]
I don't remember the specifics of how the Oauth protocol works (it's been a long while). If someone that is more familiar with this (or can trace the Android code) can confirm, it would be great.

**Comment by csoni111** [comment]
@codedentwickler I can help you with the specifics of Login api:
A POST request is to be made to `/api2/oauth/token?grant_type=password` with following params: `client_id`, `client_secret`, `username`, `password` in the post body with `application/x-www-form-urlencoded` as the content-type.
If successful, you will receive a `200 HTTP OK` json type response, with a `access_token` field in the response. This access_token has to be stored for further calls to the api.
Also the api does not provide any expiration time, but if the further calls do not succeed or report an invalid token then we will have to logout the user and send him back to login screen.

**Comment by codedentwickler** [comment]
Thanks, @cpg @csoni111. This helps a lot. I understand how it works now. 
I will check out the Android code to learn more about how it was implemented if I need anything more.

**Comment by codedentwickler** [comment]
@cpg @csoni111 I have integrated OAuth according to what you described earlier, but I still need to test with the actual endpoints and credential to check if it works. 

What is the next step?

**Comment by codedentwickler** [comment]
@cpg @csoni111  I just created a PR for the OAuth and login Implementation. Kindly review.

**Comment by eliakorkmaz** [comment]
@cpg I got two question, expect this requirements can I add another components which I think its fit with the app for now, and the other is, will you reply to whose send the Amahi Gsoc form ?

**Comment by cpg** [comment]
@eliakorkmaz These two things appear to be unrelated to this issue. Please file a separate issue with your suggestion. The second question is not appropriate to an issue at all (we will eventually send a welcome message).

**Comment by eliakorkmaz** [comment]
@cpg deleted the own comment, sorry for at all, I will bring questions with new issues.

**Comment by baquer** [comment]
@cpg can we use "skip" button in login page to skip the login and and thats directly connects to the dashboard from where we can directly connects other components , and it provides an easiness to the contributors who are working in this project and when this project finishes, we will remove that skip button

**Comment by cpg** [comment]
@baquer 1) The app remembers credentials going forward (I will merge that after I can test it more), so this UI change is not really that necessary. 2) It can lead to accidents later, so I would say you can add it for yourself if you want, but not commit it. 3) Credentials will be needed to access the right servers soon, so that will not help much going forward.

**Comment by baquer** [comment]
Okay
