### ISSUE TITLE
Chromecast Support

### ISSUE THREAD

**Issue by baquer** [amahi/ios#40]
**Chromecast Support**

Chromecast support  lets you stream  videos and  audio from your Amahi app  to your TV or speakers.

**Setup**

Using Cocoapods

pod ‘google-cast-sdk’
pod ‘google-cast-remote-display-sdk’

**Steps To Be Perform**
 
 -> Install Cocoapods
 -> Add cast Button
 -> Devices Scanning
 -> Select device after Scanning 
 -> work with media channel i.e. Media control Channel
 -> load the media
 -> Define Media Information.
 -> Cast the media
 -> Add mini controller 
 -> Add Expanded controller
 -> Before publishing we need to run shell **script strip_unused_archs.sh** to strip unused 
      architectures from the app bundle

**Comment by cpg** [comment]
how would you plan to test it?

the app itself has no way to play video at the moment (hopefully soon, so why not wait until then?).

what is the relationship of strip_unused_archs.sh to CC?

**Comment by baquer** [comment]
I don't have Chromecast device presently so i am not able to test the app , but i will find out the way for testing . As the app has no way to play video at the moment ,so i will wait until it gets implemented 
If we add Google cast using cocoapods, we don't need to strip. If we added it manually, then we must add the script to remove them, because the problem is that the  framework contains a build for both the simulator (x86_64) and the actual devices (ARM).So we aren't allowed to submit to the App Store a binary for an unsupported architecture, and it will give an error of ERROR ITMS-90087 while publishing the app to app store.

**Comment by ZiyadKhalil** [comment]
Hi @cpg , 
Can you remove the on hold and enhancement labels since the app now has a video player?
