### ISSUE TITLE
File names are sometimes long, sometimes shortened with dots

### ISSUE THREAD

**Issue by cpg** [amahi/ios#46]
There are some inconsistencies in the way labels are presented. I am not sure what's happening, so these things below are my observations, with my data set.

Definition `ellipsized`: a word I just made up to mean reducing the length of a label or name and an ellipsis `...` placed at the end of the reduced label. (surely there is a name for this already?)

If the rendering is wide first, the longest labels[*] are ellipsized to fit. If the device is rotated to a shorter view, it appears the labels are shortened further dynamically. another rotation to wide works well. * however, some names that are not too long have been ellipsized unnecessarily already in the wide view, for some reason that I can't understand. This also happens in ultra-wide devices like an iPad.

Now, if the rendering is vertical first (_I think_), it appears that perhaps the length is determined by that. So the labels are ellipsized, but when rotated, but the ellipsized labels are not expanded. Interestingly, doing a pull-down-to-refresh does not help. I am not sure this is a big deal, as probably the user would not want to lose what they are looking at, so re-rendering may lose the focus?

There is a lot of room for intelligent algorithms here.

For example, it's common that there are many files with the same name, e.g. for audio books, or TV show episodes, 
```
The Today Show Starring Some Guy or Gal - 5x11 - Tyler Perry, Lea Michele, Jhene Aiko, Big Sean.mkv
```
So they show up as  `The Today Show Starring Some Guy or Gal -  ...` or something like that.

So, one smart thing to do may be to detect if all files (or virtually all, for brownie points) have the exact same beginning, they could all be removed and displayed without the common string, i.e., `5x11 - Tyler Perry, Lea Michele, Jhene Aiko, Big Sean.mkv`. Perhaps the common subexpression could be used as a "group label" and all the rest could be indented below the group label (like a "virtual folder").

**Comment by csoni111** [comment]
How about if we ellipsize it from the middle, like:
`The Today Show Starring ... Lea Michele, Jhene Aiko, Big Sean.mkv`

**Comment by cpg** [comment]
Good idea!

If ellipsized in the same place it should all align, so it should probably work readability-wise!

**Comment by cpg** [comment]
[ellipsize](https://developer.android.com/reference/android/widget/TextView.html#attr_android:ellipsize) is a thing. great.
