### ISSUE TITLE
video player: button to select audio track

### ISSUE THREAD

**Issue by cpg** [amahi/ios#54]
the player should have a button to select the audio track when the video has multiple audio tracks.

the button should come up visually enabled if there is more than one audio track or visually disabled (or not shown at all) if there is only one audio track.

**Comment by shubhendra-20** [comment]
I worked on this. Kindly have a look.
<img width="667" alt="Screenshot 2019-03-31 11 12 25" src="https://user-images.githubusercontent.com/37156857/55285279-1c8a1a00-53a6-11e9-8631-503c1c7f553d.png">

**Comment by cpg** [comment]
Merged
