### ISSUE TITLE
video player: selecting subtitles

### ISSUE THREAD

**Issue by cpg** [amahi/ios#59]
implement a ui for selecting subtitles

the ui should present options or each subtitle found in the media (if any).

**Comment by baquer** [comment]
I made a UI for selecting subtitles
![screen shot 2018-03-21 at 3 45 48 am](https://user-images.githubusercontent.com/32494694/37685783-bef630f8-2cba-11e8-9519-fa9876f39902.png)
I would like to work on this issue.

**Comment by cpg** [comment]
Definitely *not*, please. You said you would work on the settings area. One thing at a time.

**Comment by shubhendra-20** [comment]
I came up with a UI for selecting subtitles.
How does it look?

<img width="666" alt="Screenshot 2019-03-30 14 52 45" src="https://user-images.githubusercontent.com/37156857/55274176-86011e80-52fb-11e9-88e5-e65728274fe5.png">

**Comment by cpg** [comment]
It looks good. I would suggest using the [typical icon for CC](https://bd23.https.cdn.softlayer.net/80BD23/142.4.51.106/blog/wp-content/uploads/2008/01/subtitles-icon.png)

**Comment by iswiftshek** [comment]
I thought of a UI for the video player. Though the notion of using a direct subtitles button sounds good (@shubhendra-20 , looks great), but it will make the screen look kind of over packed at the top with other buttons like Cast, Share, Metadata, Audio Track.

How does this look?

![Screenshot 2019-04-04 at 12 49 50 AM](https://user-images.githubusercontent.com/31038198/55740202-354e9b80-5a48-11e9-9fd9-0b0c427b3c9d.png)
![Screenshot 2019-04-04 at 1 06 12 AM](https://user-images.githubusercontent.com/31038198/55740117-105a2880-5a48-11e9-8760-981132e3bbde.png)

We can have the menu button show the options of Captions and Audio Track, plus more if we wish to add. An example of this design is YouTube.

**Comment by cpg** [comment]
Merged in #184
