### ISSUE TITLE
settings area requirements

### ISSUE THREAD

**Issue by cpg** [amahi/ios#6]
We will need a settings area for the app.

At the moment we have the following settings:

 * "Connection" switch: a 3-position chooser/switch, Autodetect (default), LAN and Remote
 * A way to "Sign out" of the app back to the login screen
 * An "About" area with the version of the app. We need to identify where this version is picked up from. Maybe a constant in the code for now.
 * A "Feedback" button/link to kick off an email with an email client to support at amahi dot org with Subject "iOS Amahi Anywhere"
 * A "Rate" button/link to let the user rate the app. Please be aware that there may be specific for doing this in iOS for compliance with app store

W may add more settings as we go along.

It has to look clean, needless to say.

**Comment by snuff4** [comment]
@cpg An UI like this to start with?
Left some space for future settings.

The home icon takes back to the mai view controller.

![simulator screen shot - iphone 8 - 2018-02-19 at 21 55 03_iphone8gold_portrait](https://user-images.githubusercontent.com/30552772/36387798-f2fdbe96-15bf-11e8-8e4c-63ccc3ec8dc8.png)

**Comment by baquer** [comment]
![screen shot 2018-02-20 at 2 03 22 am](https://user-images.githubusercontent.com/32494694/36396148-83ea41b4-15e2-11e8-9504-05f45f097b58.png)
@cpg is this okay or should i need to do some changes ?

**Comment by snuff4** [comment]
@cpg Updated.

![Uploading Simulator Screen Shot - iPhone X - 2018-02-20 at 05.08.19_iphonexspacegrey_portrait.png…]()

**Comment by cpg** [comment]
Nicely done.

However, on second thought, I think it may be simpler to either have a "<" back link. or a hamburger menu to get back to.

I think we need some overall UI design (also, note that the overall look will change, per #11).

So, perhaps wait until #11 is completed and then we go to that?

**Comment by snuff4** [comment]
@cpg Yes I want to have that < back link, now that dice in the middle looks a little odd.

#11 Perfect. I use a full black background in my apps and it looks...good.

**Comment by snuff4** [comment]
Actually, the hamburger button looks better. Let me implement that, and get back to you.

**Comment by cpg** [comment]
@baquer hold off on this, as @snuff4 propose something earlier (your suggestion looked good, though).

**Comment by baquer** [comment]
if @snuff4 is not working on this ,i would like to work on this.

**Comment by snuff4** [comment]
@baquer sure.

**Comment by cpg** [comment]
@baquer wrote that he will work on it. and provided some UI for the Settings area. I will follow with my feedback below this

![screen shot 2018-03-12 at 1 42 53 am](https://user-images.githubusercontent.com/32494694/37258003-168e8de0-2597-11e8-883c-f72df2d9f642.png)
![screen shot 2018-03-12 at 1 42 58 am](https://user-images.githubusercontent.com/32494694/37258007-1e463312-2597-11e8-9e5e-06b87390c879.png)

**Comment by cpg** [comment]
My feedback:

 * The header in light gray does not match the theme, obviously. It will have to match the existing setup for colors, etc.
 * The icon is all cut off. That's just bad UI
 * As for the items, it's unclear if some of them may be unimplemented. Do not add any meny\u

These should go without saying, as it's common sense, but here it goes
 * There is browsing functionality on the app, so it 1) should not be broken by this 2) it should be integrated smoothly so the user knows what to do to get back to the rest of the app from here
 * The existing Sign Out in the header should no longer be used
 * The new Sign Out should probably give a confirmation/cancellation option

**Comment by cpg** [comment]
The settings area has to contain a three-way switch - `Automatic`, `LAN`, `Remote` like the existing app. However, it need only implement LAN and Remote for now.

Automatic mode will be implemented separately and hooked up to the `Automatic` setting afterwards under a separate issue.

**Comment by cpg** [comment]
The default must be LAN mode for now.
