### ISSUE TITLE
video player: fading of UI elements should start after play starts

### ISSUE THREAD

**Issue by cpg** [amahi/ios#60]
currently, fading of UI elements starts shortly after the player takes the screen. often, play takes a few seconds to start (possibly buffering?), but the UI has faded, so it can be a little worrying to see a black screen.

the fading should start after play starts, ideally one second in or so after play actually starts.

**Comment by codedentwickler** [comment]
I will like to work on this update. @cpg Assign it to me

**Comment by cpg** [comment]
could we do one at at time? i will assign it to you, however, I would like it if we can work towards closing the last bits of the "forwarding/bactracking 15s at a time"  #51  first.

**Comment by cpg** [comment]
I thought we agreed the controls must stay on the screen when the video is paused.

I don't seem to see that behavior. If it's simple, we should do it.
