### ISSUE TITLE
implement local access mode

### ISSUE THREAD

**Issue by cpg** [amahi/ios#62]
since we don't have a settings area yet (!), we need a way to select local access mode.

a simple ad-hock would be a simple switch or comment in the code to enable this, without ui.

an even simpler thing would be to point out where the IP of the file server can be overridden, so local access can be tested.

**Comment by csoni111** [comment]
Changing on this line in [AmahiAnywhere/Data/Remote/ApiCalls/ServerApi.swift#L44](https://github.com/amahi/ios/blob/6757f27e635bd037f3e02a6f94531557676a1a2b/AmahiAnywhere/AmahiAnywhere/Data/Remote/ApiCalls/ServerApi.swift#L44):
from
```
self.serverAddress = serverRoute.relay_addr
```
to 
```
self.serverAddress = serverRoute.local_addr
```
would do the job.
