### ISSUE TITLE
video player: gestures strategy

### ISSUE THREAD

**Issue by cpg** [amahi/ios#64]
We need some strategy/planning for gestures while the app is in the video player. Ideally, we would have these:
* ~swipe up/down anywhere: volume up/down~
* tap or double-tap ... multiple tap in the left of right of the screen moves play head back or forward by an extra 15s
* in the yet-to-exist scroll bar -- when dragging on the scrollbar position head, the play head is scrolled by that much in the video file. Ideally, if the drag is lowered in the screen, the scrolling speed is slowed down proportionally to the distance from the scrollbar

**Comment by iswiftshek** [comment]
Is there any specific value by which we should change the volume on swiping up/down? 
Or, should we let it correspond to the swipe made?

**Comment by iswiftshek** [comment]
@cpg @codedentwickler @csoni111 
Is it not possible to change the volume in MobileVLCKit?
I tried doing so, but any attempts to change the volume mutes it out completely. 
So do we have to change the system volume by importing MediaPlayer instead?

**Comment by csoni111** [comment]
https://github.com/videolan/vlckit/blob/5abdec40accaf53e2966e5ee00469630dc88e7ce/Tests/Sources/VLCAudioTest.swift#L88:L105
Check this audio volume change test on VideoLan official repo. Does this
not work? @iswiftshek

**Comment by iswiftshek** [comment]
Oh, yes, figured that out. I missed the type cast to Int32.
Thank you!

**Comment by shubhendra-20** [comment]
Would it not be better if swiping up/down in the right half portion of the screen controlled volume while in the left half adjusted brightness or contrast?

**Comment by cpg** [comment]
Most of it is merged in #144
