### ISSUE TITLE
video player: sample good UI

### ISSUE THREAD

**Issue by cpg** [amahi/ios#66]
here are some sample images of a video player (an html5 one in a browser) that is kind of nice looking.  I think we should get inspiration from it.

There samples, ipad, iphone vertical, iphone horizontal.

Notice how the grey areas are really just white (or light gray) but **translucent**.

![img_e0041](https://user-images.githubusercontent.com/9907/37751708-2e2c8350-2d51-11e8-8e59-0e609d7bf90d.JPG)
![img_7053](https://user-images.githubusercontent.com/9907/37751709-2e583086-2d51-11e8-873f-d94512cd8230.jpg)
![img_7059](https://user-images.githubusercontent.com/9907/37751710-2e873dcc-2d51-11e8-8f7b-25031f6c5ff2.jpg)

**Comment by baquer** [comment]
Not sure about the first one , but the last two images are the images of AVPlayer , we can easily import this AVPlayer By AVKit.  We can use an AVPlayer to play local and remote file-based media, such as QuickTime movies and MP3 audio files, as well as audiovisual media served using HTTP Live Streaming.
We can easily Use this player in our App By just 3 lines of code 
import AVKit
let moviePlayer = AVPlayerViewController()
 moviePlayer.player = AVPlayer(url: URL(fileURLWithPath: videoFile!))
 present(moviePlayer, animated: true, completion: nil)

**Comment by cpg** [comment]
This comment, while well intentioned, is out of place. This is about UI not about the stack we use for playing video. We have already decided and started integration of VLCKit.

**Comment by codedentwickler** [comment]
@cpg Drawing from the suggestions above, I'm making an update to the current UI of the video player. This update will enable us to implement the scrobbling feature referenced here #52. 

* NOTE: The size of Thumb of the slider will be reduced. 
![screen shot 2018-04-18 at 3 00 36 am](https://user-images.githubusercontent.com/18694890/38907751-276ee656-42b5-11e8-896a-a4ec15bebae6.png)
