### ISSUE TITLE
app crashes hard after audio file finishes playing

### ISSUE THREAD

**Issue by cpg** [amahi/ios#77]
details of the crash: https://paste.fedoraproject.org/paste/zoYyynX5H23OV7uMhrnk0g/raw

to reproduce: play an mp3 audio file and let it play until the end (or fast forward to near the end and let it finish playing)

**Comment by cpg** [comment]
Reproducible in the demo server
![screen shot 2018-04-06 at 4 13 22 pm](https://user-images.githubusercontent.com/9907/38448498-5f50b842-39b9-11e8-9b96-71306412d5d0.png)

**Comment by cpg** [comment]
Actually, I believe this also happens when a video file ends playing. I am not 100% sure, as I was not connected to it, but it acted the same -- reproduction ends and the app crashes.

**Comment by codedentwickler** [comment]
This bug has been fixed in #80
