### ISSUE TITLE
add crashlytics

### ISSUE THREAD

**Issue by cpg** [amahi/ios#81]
directions: https://fabric.io/kits/ios/crashlytics/install

i don't know how to add the api key in a sensible way for an open source project.

i'd think we need to keep the api key in our ApiConfig swift file.

**Comment by codedentwickler** [comment]
Went through Crashlytics installation docs. Seems we need to add the configuration keys to the project's `info.plist` file. This key will be public if we do this, not sure if there is another way to do this. We can't reference ApiConfig.swift in the info.plist.

**Comment by cpg** [comment]
Here are [some pointers](https://github.com/search?l=Swift&q=crashlytics&type=Code) to explore.

**Comment by jogendra** [comment]
@cpg @codedentwickler This answer may be little helpful https://stackoverflow.com/questions/48488531/best-practice-for-using-fabric-crashlytics-with-open-source-app
