### ISSUE TITLE
Unable to resolve the color named "textMutedColor"

### ISSUE THREAD

**Issue by cpg** [amahi/ios#82]
```
WARNING: Unable to resolve the color named "textMutedColor" from any of the following bundles: com.amahi.AmahiAnywhere-dev, com.amahi.AmahiAnywhere-dev
```

**Comment by cpg** [comment]
The message in #78 could be related to this too, so we may want to try lowering the deployment target.

**Comment by codedentwickler** [comment]
Noticed this issue yesterday in the logs. Seems Xcode is referencing a color type in assets that do not exist. I'm removing all reference to this color `textMutedColor ` in the project. That will fix this.

**Comment by codedentwickler** [comment]
I have confirmed this warning does not relate lower iOS version
