### ISSUE TITLE
video controls sometimes do not vanish

### ISSUE THREAD

**Issue by cpg** [amahi/ios#97]
i have seen this but not been able to reproduce it.

the video controls sometimes stay up until the whole duration of the video, for no reason.

**Comment by cpg** [comment]
when this happens, one apparently _can_ touch the screen and that makes them fade out after a few seconds.

**Comment by codedentwickler** [comment]
This might be caused sometimes because we invalidated the timer and for some weird reasons (currently unknown ), the timer was not restarted the next time the user touched the screen.

**Comment by cpg** [comment]
I *think* after the controls stay up, the user can tap and they disappear.

So that narrows the scope of the bug, I believe.

**Comment by cpg** [comment]
I think i can reproduce this!

Opening `.avi` files appears to leave the controls open after play starts.
